# signet_core.py

import cv2
import imagehash
from PIL import Image
from fpdf import FPDF
import os
import datetime

# --- 1. ALGORITMA PHASH (VIDEO & IMAGE) ---

def calculate_video_phash(video_path):
    if not os.path.exists(video_path): return None
    try:
        cap = cv2.VideoCapture(video_path)
        if not cap.isOpened(): return None
        frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        mid_frame = max(0, frame_count // 2)
        cap.set(cv2.CAP_PROP_POS_FRAMES, mid_frame)
        ret, frame = cap.read()
        cap.release()
        if not ret: return None
        img = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        pil_img = Image.fromarray(img)
        p_hash = imagehash.phash(pil_img, hash_size=16)
        return str(p_hash)
    except Exception as e:
        print(f"❌ Error Video Hash: {e}")
        return None

# 🔥 FUNGSI BARU: HASH GAMBAR
def calculate_image_phash(image_path):
    if not os.path.exists(image_path): return None
    try:
        # Buka langsung pakai Pillow
        pil_img = Image.open(image_path)
        p_hash = imagehash.phash(pil_img, hash_size=16)
        return str(p_hash)
    except Exception as e:
        print(f"❌ Error Image Hash: {e}")
        return None

def calculate_hamming_distance(hash1_str, hash2_str):
    try:
        h1 = imagehash.hex_to_hash(hash1_str)
        h2 = imagehash.hex_to_hash(hash2_str)
        return h1 - h2
    except:
        return 999 

# --- 2. EVIDENCE GENERATOR ---

class EvidencePDF(FPDF):
    def header(self):
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'SIGNET: IP INFRINGEMENT REPORT', ln=1, align='C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Generated by SIGNET on Story Protocol - Page {self.page_no()}', align='C')

def clean_text(text):
    return str(text).encode('latin-1', 'replace').decode('latin-1')

def generate_takedown_pdf(scam_filename, original_ip_id, similarity_score, tx_hash):
    pdf = EvidencePDF()
    pdf.add_page()
    
    pdf.set_font("Helvetica", size=12)
    pdf.cell(0, 10, txt=f"Date: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", ln=1)
    pdf.cell(0, 10, txt=f"Report ID: SIG-{int(datetime.datetime.now().timestamp())}", ln=1)
    pdf.ln(10)

    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, txt="VIOLATION DETECTED", ln=1)
    
    pdf.set_font("Helvetica", size=12)
    content_text = (
        f"Target Content: {clean_text(scam_filename)}\n"
        f"Violated Asset: Story Protocol IP #{clean_text(original_ip_id)}\n"
        f"Visual Similarity: {similarity_score}% (High Confidence)"
    )
    pdf.multi_cell(0, 10, txt=content_text)
    pdf.ln(10)

    pdf.set_font("Helvetica", 'B', 14)
    pdf.cell(0, 10, txt="ON-CHAIN EVIDENCE", ln=1)
    
    pdf.set_font("Courier", size=10)
    pdf.multi_cell(0, 10, txt=f"Blockchain: Story Odyssey Testnet\nTx Hash:\n{clean_text(tx_hash)}")
    pdf.ln(10)
    
    pdf.set_font("Helvetica", 'I', 10)
    pdf.multi_cell(0, 8, txt="This document serves as cryptographic proof of IP infringement.")

    output_filename = f"takedown_report_{original_ip_id}.pdf"
    pdf.output(output_filename)
    return output_filename